### ISSUE TITLE
selection of characters

### ISSUE THREAD

**Issue by c1au6i0** [sigbertklinke/abbreviate#1]
Hello I have 1 question and 1 comment regarding the following code:

```
abbreviate::abbreviate_text(c("aab", "aac", "aad"), minlength = 1)
#>  aab  aac  aad 
#> "aa" "ac" "ad"
```

1) `minlength` is an  integer indicating the minimum length of the abbreviations. However with 1 is abbreviating to elements of length 2, shouldn't they be of length 1? 

2) In a case as the one above  I would expect to obtain `b`, `c` & `d`  (or `ab`, `ac`, `ad` for length 2) since that is the letter that identify uniquely the abbreviation.

Thank you

**Comment by sigbertklinke** [comment]
Hello,

1. No, it is a minimal length. Therefore the abbreviations can be longer than this.
2. The main aim of abbreviate_text is to get "readable" abbreviations as in the examples and not to find the shortest abbreviations. However, you can use

```
> abbreviate_text(c("aab", "aac", "aad"), minlength=0)
aab aac aad 
"a" "c" "d" 
```
